# Generated by Django 3.0.3 on 2020-07-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atoz_store', '0002_auto_20200701_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='fruit',
            fields=[
                ('name', models.CharField(max_length=128)),
                ('id', models.IntegerField(max_length=128, primary_key=True, serialize=False)),
                ('price', models.IntegerField(max_length=128)),
            ],
        ),
    ]
