# Generated by Django 3.0.3 on 2020-07-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atoz_store', '0003_fruit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fruit',
            name='price',
            field=models.IntegerField(),
        ),
    ]
