# Generated by Django 3.0.3 on 2020-07-01 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atoz_store', '0004_auto_20200701_1507'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fruit',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
