# Generated by Django 3.0.3 on 2020-08-02 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atoz_store', '0005_something'),
    ]

    operations = [
        migrations.DeleteModel(
            name='something',
        ),
    ]
