# Generated by Django 3.0.3 on 2020-08-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atoz_store', '0008_extendeduser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catagory',
            field=models.CharField(choices=[('FR', 'fruit'), ('DR', 'dryfruit'), ('VG', 'vegitable'), ('oth', 'other')], max_length=30, null=True),
        ),
    ]
