# Generated by Django 3.0.3 on 2020-08-09 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atoz_store', '0009_product_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catagory',
            field=models.CharField(choices=[('fruit', 'fruit'), ('dryfruit', 'dryfruit'), ('vegitable', 'vegitable'), ('other', 'other')], max_length=30, null=True),
        ),
    ]
