# Generated by Django 3.0.3 on 2020-08-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atoz_store', '0011_shipping_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='status',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('orderprocessing', 'order processing'), ('outfordelivery', 'out for delivery'), ('delivered', 'delivered')], max_length=40, null=True),
        ),
    ]
