# Generated by Django 3.0.3 on 2020-07-21 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atoz_store', '0012_auto_20200721_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='address',
        ),
        migrations.AddField(
            model_name='shipping',
            name='adress',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='atoz_store.Customer'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='atoz_store.Customer'),
        ),
    ]
