# Generated by Django 3.0.3 on 2020-08-10 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atoz_store', '0014_auto_20200809_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='Orderm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='atoz_store.Order'),
        ),
    ]
