# Generated by Django 3.0.3 on 2020-08-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atoz_store', '0015_auto_20200810_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('op', 'order processing'), ('od', 'out for delivery'), ('d', 'delivered')], max_length=40, null=True),
        ),
    ]
