# Generated by Django 3.0.3 on 2020-08-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atoz_store', '0017_auto_20200811_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='payment',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
