# Generated by Django 3.0.3 on 2020-09-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atoz_store', '0019_auto_20200831_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mini_desc',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
