# Generated by Django 3.0.3 on 2020-07-24 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atoz_store', '0020_auto_20200724_0701'),
    ]

    operations = [
        migrations.CreateModel(
            name='manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Orderm', models.CharField(max_length=1000, null=True)),
                ('namem', models.CharField(max_length=400, null=True)),
                ('phonem', models.IntegerField(null=True)),
                ('productm', models.CharField(max_length=400, null=True)),
                ('quantitym', models.CharField(max_length=400, null=True)),
                ('adressm', models.CharField(max_length=400, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='atoz_store.Customer'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='atoz_store.Customer'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='phonenumber',
            field=models.IntegerField(default=404),
        ),
    ]
