# Generated by Django 3.0.3 on 2020-09-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atoz_store', '0020_product_mini_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
        migrations.AddField(
            model_name='product',
            name='alias',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
