# Generated by Django 3.0.3 on 2020-09-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atoz_store', '0020_auto_20200902_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catagory',
            field=models.CharField(choices=[('fruits', 'fruits'), ('dryfruits', 'dryfruits'), ('vegetable', 'vegetable'), ('other', 'other')], max_length=30, null=True),
        ),
    ]
