# Generated by Django 3.0.3 on 2020-09-11 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atoz_store', '0021_auto_20200902_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='alias',
            field=models.CharField(default='null', max_length=30, null=True),
        ),
    ]
