# Generated by Django 3.0.8 on 2020-09-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atoz_store', '0022_auto_20200912_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catagory',
            field=models.CharField(choices=[('fruit', 'fruit'), ('dryfruit', 'dryfruit'), ('vegitable', 'vegitable'), ('chicken', 'chicken'), ('seafood', 'seafood'), ('other', 'other')], max_length=30, null=True),
        ),
    ]
