# Generated by Django 3.0.3 on 2020-10-02 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atoz_store', '0023_auto_20200929_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
            preserve_default=False,
        ),
    ]
