# Generated by Django 3.0.3 on 2020-10-03 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atoz_store', '0024_product_offprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offprice',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
