# Generated by Django 3.0.3 on 2020-07-24 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atoz_store', '0025_auto_20200725_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prodtype',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='atoz_store.Customer'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='atoz_store.Customer'),
        ),
    ]
